# For development only

name: databridge
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DATABASE_ADMIN_USER}
      POSTGRES_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
    container_name: databridge-database
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: databridge-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
  
  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    


  loki:
    image: grafana/loki:latest
    container_name: databridge-loki
    ports:
      - '3100:3100'

  grafana:
    image: grafana/grafana:latest
    container_name: databridge-grafana
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: 'false'
 
    depends_on:
      - loki
      - prom-server


volumes:
  pg-data:
  redis-data:
